/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author hp
 */
public class AgregarAntecedentes extends javax.swing.JPanel {

    /**
     * Creates new form AgregarAntecedentes
     */
    public AgregarAntecedentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelComponentes = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lbTipoDelito = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        lbLinea = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JPanel();
        lbBuscar = new javax.swing.JLabel();
        IconoBuscar = new javax.swing.JLabel();
        lbNombreApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbArt = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxTipoDelito = new javax.swing.JComboBox<>();
        lbDelito = new javax.swing.JLabel();
        txArt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbJuzgado = new javax.swing.JLabel();
        cbxJuzgados = new javax.swing.JComboBox<>();
        lbDescripcionDelito1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 610));
        setLayout(null);

        PanelComponentes.setPreferredSize(new java.awt.Dimension(10, 313));

        LabelTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        LabelTitulo.setText("AGREGAR ANTECEDENTES");
        LabelTitulo.setToolTipText("");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lbTipoDelito.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbTipoDelito.setText("Tipo de Delito:");
        lbTipoDelito.setToolTipText("");

        txtNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApellidoActionPerformed(evt);
            }
        });

        lbLinea.setText("________________________________________________________________________________________________________________________________________________________________________");

        BotonBuscar.setBackground(new java.awt.Color(18, 44, 82));

        lbBuscar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(204, 206, 223));
        lbBuscar.setText("Buscar");
        lbBuscar.setToolTipText("");

        IconoBuscar.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        IconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoBuscar1.png"))); // NOI18N
        IconoBuscar.setToolTipText("");

        javax.swing.GroupLayout BotonBuscarLayout = new javax.swing.GroupLayout(BotonBuscar);
        BotonBuscar.setLayout(BotonBuscarLayout);
        BotonBuscarLayout.setHorizontalGroup(
            BotonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonBuscarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoBuscar)
                .addContainerGap())
        );
        BotonBuscarLayout.setVerticalGroup(
            BotonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonBuscarLayout.createSequentialGroup()
                .addGroup(BotonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbNombreApellido.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNombreApellido.setText("Nombre y Apellido");
        lbNombreApellido.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");

        lbCedula.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbCedula.setText("Cédula");
        lbCedula.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        lbArt.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbArt.setText("Art:");
        lbArt.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");

        cbxTipoDelito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbDelito.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDelito.setText("Delito:");
        lbDelito.setToolTipText("");

        txArt.setText("N");
        txArt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txArt.setEnabled(false);
        txArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txArtActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        lbJuzgado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbJuzgado.setText("Juzgado:");
        lbJuzgado.setToolTipText("");

        cbxJuzgados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbDescripcionDelito1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDescripcionDelito1.setText("Descripción:");
        lbDescripcionDelito1.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");

        javax.swing.GroupLayout PanelComponentesLayout = new javax.swing.GroupLayout(PanelComponentes);
        PanelComponentes.setLayout(PanelComponentesLayout);
        PanelComponentesLayout.setHorizontalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(LabelTitulo))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbCedula)
                        .addGap(568, 568, 568)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(lbNombreApellido))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(401, 401, 401)
                        .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLinea))
                .addGap(67, 67, 67))
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lbTipoDelito))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDescripcionDelito1)
                                    .addComponent(lbDelito)
                                    .addComponent(lbJuzgado))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbxJuzgados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 210, Short.MAX_VALUE))
                                .addGap(63, 63, 63)
                                .addComponent(lbArt)
                                .addGap(18, 18, 18)
                                .addComponent(txArt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelComponentesLayout.setVerticalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addComponent(LabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbCedula)
                    .addComponent(jLabel5)
                    .addComponent(lbNombreApellido))
                .addGap(20, 20, 20)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTipoDelito)
                        .addComponent(cbxTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDelito)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbArt)
                        .addComponent(txArt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addComponent(lbDescripcionDelito1)
                        .addGap(84, 84, 84)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxJuzgados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJuzgado)
                            .addComponent(jLabel19)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(PanelComponentes);
        PanelComponentes.setBounds(0, 0, 1000, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApellidoActionPerformed

    private void txArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txArtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonBuscar;
    private javax.swing.JLabel IconoBuscar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelComponentes;
    private javax.swing.JComboBox<String> cbxJuzgados;
    private javax.swing.JComboBox<String> cbxTipoDelito;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbArt;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbDelito;
    private javax.swing.JLabel lbDescripcionDelito1;
    private javax.swing.JLabel lbJuzgado;
    private javax.swing.JLabel lbLinea;
    private javax.swing.JLabel lbNombreApellido;
    private javax.swing.JLabel lbTipoDelito;
    private javax.swing.JTextField txArt;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreApellido;
    // End of variables declaration//GEN-END:variables
}
