/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import ControlAdminDatos.Utiles.Utiles;
import Controlador.ControladorPersona;
import Vista.Utiles.TablaPersonas.ConvertirEnums;
import Vista.Utiles.TablaPersonas.EstadoCivil;
import Vista.Utiles.TablaPersonas.Sexo;
import Vista.Utiles.UtilesFecha;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author hp
 */

public class AgregarPersonas extends javax.swing.JPanel {

    /**
     * Creates new form AgregarPersonas
     */
    UtilesFecha fech=new UtilesFecha();
    Utiles uti=new Utiles();
    public AgregarPersonas() {
        initComponents();
        ConvertirEnums enums=new ConvertirEnums();
        cbTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte"}));
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(enums.convertEstadoCivil(EstadoCivil.values())));
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(enums.convertSexo(Sexo.values())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcFechaN = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        cbTipoIdentificacion = new javax.swing.JComboBox<>();
        cbSexo = new javax.swing.JComboBox<>();
        foto = new rojerusan.RSFotoCircle();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 610));
        setPreferredSize(new java.awt.Dimension(1000, 610));
        setLayout(null);
        add(jSeparator1);
        jSeparator1.setBounds(10, 50, 980, 10);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Personas");
        add(jLabel1);
        jLabel1.setBounds(50, 10, 320, 40);

        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        add(txtApellidos);
        txtApellidos.setBounds(150, 150, 290, 30);

        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono);
        txtTelefono.setBounds(150, 330, 290, 30);

        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        add(txtNombres);
        txtNombres.setBounds(150, 90, 290, 30);

        jLabel2.setForeground(new java.awt.Color(49, 49, 49));
        jLabel2.setText("Cell");
        add(jLabel2);
        jLabel2.setBounds(150, 310, 290, 14);

        jLabel3.setForeground(new java.awt.Color(49, 49, 49));
        jLabel3.setText("Estado Civil");
        add(jLabel3);
        jLabel3.setBounds(530, 130, 290, 14);

        jLabel4.setForeground(new java.awt.Color(49, 49, 49));
        jLabel4.setText("Apellidos");
        add(jLabel4);
        jLabel4.setBounds(150, 130, 290, 14);

        dcFechaN.setBackground(new java.awt.Color(255, 255, 255));
        dcFechaN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        dcFechaN.setDateFormatString("dd/MM/yyyy");
        dcFechaN.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));
        add(dcFechaN);
        dcFechaN.setBounds(150, 210, 290, 30);

        jLabel5.setForeground(new java.awt.Color(49, 49, 49));
        jLabel5.setText("Fecha de nacimiento");
        add(jLabel5);
        jLabel5.setBounds(150, 190, 290, 14);

        txtMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        add(txtMail);
        txtMail.setBounds(150, 270, 290, 30);

        jLabel6.setForeground(new java.awt.Color(49, 49, 49));
        jLabel6.setText("E-mail");
        add(jLabel6);
        jLabel6.setBounds(150, 250, 290, 14);

        jLabel7.setForeground(new java.awt.Color(49, 49, 49));
        jLabel7.setText("Dirección");
        add(jLabel7);
        jLabel7.setBounds(150, 370, 290, 14);

        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion);
        txtDireccion.setBounds(150, 390, 290, 30);

        jLabel8.setForeground(new java.awt.Color(49, 49, 49));
        jLabel8.setText("Identificación");
        add(jLabel8);
        jLabel8.setBounds(150, 430, 290, 14);

        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        add(txtCedula);
        txtCedula.setBounds(150, 480, 290, 30);

        cbEstadoCivil.setBackground(new java.awt.Color(240, 240, 240));
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado Civil" }));
        add(cbEstadoCivil);
        cbEstadoCivil.setBounds(530, 150, 290, 30);

        cbTipoIdentificacion.setBackground(new java.awt.Color(240, 240, 240));
        cbTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Identificacion" }));
        add(cbTipoIdentificacion);
        cbTipoIdentificacion.setBounds(150, 450, 290, 30);

        cbSexo.setBackground(new java.awt.Color(240, 240, 240));
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo" }));
        add(cbSexo);
        cbSexo.setBounds(530, 90, 290, 30);

        foto.setColorBorde(new java.awt.Color(204, 204, 204));
        add(foto);
        foto.setBounds(590, 210, 130, 130);

        jLabel9.setForeground(new java.awt.Color(49, 49, 49));
        jLabel9.setText("Nombre");
        add(jLabel9);
        jLabel9.setBounds(150, 70, 290, 14);

        jLabel10.setForeground(new java.awt.Color(49, 49, 49));
        jLabel10.setText("Sexo");
        add(jLabel10);
        jLabel10.setBounds(530, 70, 290, 14);

        btnGuardar.setBackground(new java.awt.Color(18, 44, 82));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(620, 460, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed

    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed

    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed

    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed

    }//GEN-LAST:event_txtMailActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed

    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed

    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(18,79,82));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(18,44,82));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        ControladorPersona ctr=new ControladorPersona();
        ctr.newPersona();
        ctr.agregarPersona().setIdPersona(0L);
        ctr.agregarPersona().setCedula(txtCedula.getText());
        ctr.agregarPersona().setNombre(txtNombres.getText());
        ctr.agregarPersona().setApellido(txtApellidos.getText());
        ctr.agregarPersona().setFechaNacimiento(fech.getFecha(dcFechaN));
        ctr.agregarPersona().setDireccion(txtDireccion.getText());
        ctr.agregarPersona().setEstadoCivil(cbEstadoCivil.getSelectedItem().toString());
        ctr.agregarPersona().setSexo(cbSexo.getSelectedItem().toString());
        ctr.agregarPersona().setTelefono(txtTelefono.getText());
        ctr.agregarPersona().setMail(txtMail.getText());
        ctr.agregarPersona().setFile(new File(foto.getRutaImagen()));
        ctr.agregarPersona().setEstado(Boolean.TRUE);
        ctr.agregarPersona().setIdRol(2L);
        ctr.guardarPersona();
        
    }//GEN-LAST:event_btnGuardarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbTipoIdentificacion;
    private com.toedter.calendar.JDateChooser dcFechaN;
    private rojerusan.RSFotoCircle foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
