/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class AgregaAntecedentes extends javax.swing.JFrame {

    boolean boolPanelMenu = false;
    boolean boolPanelAntecedentes = false;
    boolean boolPanelPersonas = false;
    boolean boolPanelSettings = false;
    File fichero;
    /**
     * Creates new form VistaAntecedentes
     */
    public AgregaAntecedentes() {
        initComponents();
        IconoBorrarArchivo.setVisible(false);
        lbIconoArchivo.setVisible(false);
        lbNombreArchivo.setVisible(false);
        rbEnProceso.setEnabled(false);
        rbEnProceso.setSelected(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconoMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        IconoInicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IconoAntecedente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IconoTrianguloAntecedente = new javax.swing.JLabel();
        PanelAntecedentess = new javax.swing.JPanel();
        IconoAgregarAntecedente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IconoEditarAntecedente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PanelPersonas = new javax.swing.JPanel();
        IconoPersonaAgregar = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        IconoPersonaEditar = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        IconoJuzgados = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        IconoSettings = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        IconoTrianguloSettings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IconoPersonas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IconoTrianguloPersonas = new javax.swing.JLabel();
        PanelSettings = new javax.swing.JPanel();
        IconoCuenta = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        IconoCerrarSesion = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelComponentes = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lbTipoDelito = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        lbLinea = new javax.swing.JLabel();
        lbNombreApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbArt = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxTipoDelito = new javax.swing.JComboBox<>();
        lbDelito = new javax.swing.JLabel();
        txArt = new javax.swing.JTextField();
        cbDelito = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbJuzgado = new javax.swing.JLabel();
        cbxJuzgados = new javax.swing.JComboBox<>();
        lbDescripcionDelito1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dcFechaInicioAudiencia = new com.toedter.calendar.JDateChooser();
        lbFechaInicioAudiencia = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbFechaInicioAudiencia1 = new javax.swing.JLabel();
        dcFechaFinalizacionAudiencia = new com.toedter.calendar.JDateChooser();
        lbDuracionAudiencia = new javax.swing.JLabel();
        txDuracionAudiencia = new javax.swing.JTextField();
        lbIntancia = new javax.swing.JLabel();
        txtIntancia = new javax.swing.JTextField();
        lbNrAudiencia = new javax.swing.JLabel();
        txtNrAudiencia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rbEnProceso = new javax.swing.JRadioButton();
        rbFinalizado = new javax.swing.JRadioButton();
        lbEstadoProceso = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbTipoCondena = new javax.swing.JLabel();
        cbxTipoCondena = new javax.swing.JComboBox<>();
        lbSentencia = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSentencia = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lbNombreArchivo = new javax.swing.JLabel();
        lbIconoArchivo = new javax.swing.JLabel();
        IconoBorrarArchivo = new javax.swing.JLabel();
        botonSubir = new javax.swing.JPanel();
        lbIconoSubir = new javax.swing.JLabel();
        lbSubirArchivo = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JPanel();
        IconoBuscar = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JPanel();
        lbIconoGuardar = new javax.swing.JLabel();
        lbGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(125, 132, 145));

        IconoMenu.setBackground(new java.awt.Color(18, 44, 82));
        IconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconoMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconoMenuMouseExited(evt);
            }
        });
        IconoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/align-justify.png"))); // NOI18N
        IconoMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        PanelMenu.setBackground(new java.awt.Color(18, 44, 82));
        PanelMenu.setMinimumSize(new java.awt.Dimension(50, 220));
        PanelMenu.setPreferredSize(new java.awt.Dimension(0, 266));

        IconoInicio.setBackground(new java.awt.Color(18, 44, 82));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCasa1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 206, 223));
        jLabel2.setText("Inicio");

        javax.swing.GroupLayout IconoInicioLayout = new javax.swing.GroupLayout(IconoInicio);
        IconoInicio.setLayout(IconoInicioLayout);
        IconoInicioLayout.setHorizontalGroup(
            IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoInicioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoInicioLayout.setVerticalGroup(
            IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IconoAntecedente.setBackground(new java.awt.Color(18, 44, 82));
        IconoAntecedente.setPreferredSize(new java.awt.Dimension(140, 46));
        IconoAntecedente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoAntecedenteMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 206, 223));
        jLabel8.setText("Antecedentes");

        IconoTrianguloAntecedente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoAntecedenteLayout = new javax.swing.GroupLayout(IconoAntecedente);
        IconoAntecedente.setLayout(IconoAntecedenteLayout);
        IconoAntecedenteLayout.setHorizontalGroup(
            IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoTrianguloAntecedente)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoAntecedenteLayout.setVerticalGroup(
            IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAntecedenteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoTrianguloAntecedente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAntecedentess.setBackground(new java.awt.Color(18, 44, 82));
        PanelAntecedentess.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoAgregarAntecedente.setBackground(new java.awt.Color(125, 132, 164));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 206, 223));
        jLabel10.setText("Agregar");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAgregar1.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 206, 223));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout IconoAgregarAntecedenteLayout = new javax.swing.GroupLayout(IconoAgregarAntecedente);
        IconoAgregarAntecedente.setLayout(IconoAgregarAntecedenteLayout);
        IconoAgregarAntecedenteLayout.setHorizontalGroup(
            IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAgregarAntecedenteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(27, 27, 27))
        );
        IconoAgregarAntecedenteLayout.setVerticalGroup(
            IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAgregarAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoAgregarAntecedenteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        IconoEditarAntecedente.setBackground(new java.awt.Color(18, 44, 82));
        IconoEditarAntecedente.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 206, 223));
        jLabel14.setText("Editar");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoEditar1.png"))); // NOI18N

        javax.swing.GroupLayout IconoEditarAntecedenteLayout = new javax.swing.GroupLayout(IconoEditarAntecedente);
        IconoEditarAntecedente.setLayout(IconoEditarAntecedenteLayout);
        IconoEditarAntecedenteLayout.setHorizontalGroup(
            IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoEditarAntecedenteLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(44, 44, 44))
        );
        IconoEditarAntecedenteLayout.setVerticalGroup(
            IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoEditarAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAntecedentessLayout = new javax.swing.GroupLayout(PanelAntecedentess);
        PanelAntecedentess.setLayout(PanelAntecedentessLayout);
        PanelAntecedentessLayout.setHorizontalGroup(
            PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAntecedentessLayout.createSequentialGroup()
                .addGroup(PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IconoEditarAntecedente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IconoAgregarAntecedente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelAntecedentessLayout.setVerticalGroup(
            PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAntecedentessLayout.createSequentialGroup()
                .addComponent(IconoAgregarAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(IconoEditarAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPersonas.setBackground(new java.awt.Color(18, 44, 82));
        PanelPersonas.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoPersonaAgregar.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonaAgregar.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAgregar1.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 206, 223));
        jLabel39.setText("Agregar");

        javax.swing.GroupLayout IconoPersonaAgregarLayout = new javax.swing.GroupLayout(IconoPersonaAgregar);
        IconoPersonaAgregar.setLayout(IconoPersonaAgregarLayout);
        IconoPersonaAgregarLayout.setHorizontalGroup(
            IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaAgregarLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(26, 26, 26))
        );
        IconoPersonaAgregarLayout.setVerticalGroup(
            IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaAgregarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addContainerGap())
        );

        IconoPersonaEditar.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonaEditar.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoEditar1.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 206, 223));
        jLabel42.setText("Editar");

        javax.swing.GroupLayout IconoPersonaEditarLayout = new javax.swing.GroupLayout(IconoPersonaEditar);
        IconoPersonaEditar.setLayout(IconoPersonaEditarLayout);
        IconoPersonaEditarLayout.setHorizontalGroup(
            IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaEditarLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addGap(44, 44, 44))
        );
        IconoPersonaEditarLayout.setVerticalGroup(
            IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaEditarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelPersonasLayout = new javax.swing.GroupLayout(PanelPersonas);
        PanelPersonas.setLayout(PanelPersonasLayout);
        PanelPersonasLayout.setHorizontalGroup(
            PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonasLayout.createSequentialGroup()
                .addGroup(PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoPersonaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPersonasLayout.setVerticalGroup(
            PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonasLayout.createSequentialGroup()
                .addComponent(IconoPersonaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        IconoJuzgados.setBackground(new java.awt.Color(18, 44, 82));
        IconoJuzgados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoJuzgadosMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoJuzgado.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 206, 223));
        jLabel24.setText("Juzgados");

        javax.swing.GroupLayout IconoJuzgadosLayout = new javax.swing.GroupLayout(IconoJuzgados);
        IconoJuzgados.setLayout(IconoJuzgadosLayout);
        IconoJuzgadosLayout.setHorizontalGroup(
            IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoJuzgadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoJuzgadosLayout.setVerticalGroup(
            IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoJuzgadosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IconoSettings.setBackground(new java.awt.Color(18, 44, 82));
        IconoSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoSettingsMouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoSettings.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 206, 223));
        jLabel26.setText("Settings");

        IconoTrianguloSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoSettingsLayout = new javax.swing.GroupLayout(IconoSettings);
        IconoSettings.setLayout(IconoSettingsLayout);
        IconoSettingsLayout.setHorizontalGroup(
            IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoTrianguloSettings)
                .addGap(13, 13, 13)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoSettingsLayout.setVerticalGroup(
            IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoSettingsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoTrianguloSettings, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(204, 206, 223));
        jLabel1.setText("___________________________________");

        IconoPersonas.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonas.setPreferredSize(new java.awt.Dimension(210, 46));
        IconoPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoPersonasMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersonas.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 206, 223));
        jLabel18.setText("Personas");

        IconoTrianguloPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoPersonasLayout = new javax.swing.GroupLayout(IconoPersonas);
        IconoPersonas.setLayout(IconoPersonasLayout);
        IconoPersonasLayout.setHorizontalGroup(
            IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoPersonasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(IconoTrianguloPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        IconoPersonasLayout.setVerticalGroup(
            IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(IconoTrianguloPersonas)
                    .addComponent(jLabel18))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelSettings.setBackground(new java.awt.Color(18, 44, 82));
        PanelSettings.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoCuenta.setBackground(new java.awt.Color(18, 44, 82));
        IconoCuenta.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCuenta.png"))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 206, 223));
        jLabel46.setText("Cuenta");

        javax.swing.GroupLayout IconoCuentaLayout = new javax.swing.GroupLayout(IconoCuenta);
        IconoCuenta.setLayout(IconoCuentaLayout);
        IconoCuentaLayout.setHorizontalGroup(
            IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCuentaLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addGap(67, 67, 67))
        );
        IconoCuentaLayout.setVerticalGroup(
            IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel44))
                .addGap(13, 13, 13))
        );

        IconoCerrarSesion.setBackground(new java.awt.Color(18, 44, 82));
        IconoCerrarSesion.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel49.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 206, 223));
        jLabel49.setText("Cerrar Sesión");

        javax.swing.GroupLayout IconoCerrarSesionLayout = new javax.swing.GroupLayout(IconoCerrarSesion);
        IconoCerrarSesion.setLayout(IconoCerrarSesionLayout);
        IconoCerrarSesionLayout.setHorizontalGroup(
            IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addGap(25, 25, 25))
        );
        IconoCerrarSesionLayout.setVerticalGroup(
            IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel47))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelSettingsLayout = new javax.swing.GroupLayout(PanelSettings);
        PanelSettings.setLayout(PanelSettingsLayout);
        PanelSettingsLayout.setHorizontalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconoCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelSettingsLayout.setVerticalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addComponent(IconoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconoCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoJuzgados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PanelPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelAntecedentess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IconoSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IconoAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IconoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IconoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(IconoAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelAntecedentess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(PanelPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IconoJuzgados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IconoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane4.setPreferredSize(new java.awt.Dimension(1072, 600));

        PanelComponentes.setBackground(new java.awt.Color(255, 255, 255));
        PanelComponentes.setPreferredSize(new java.awt.Dimension(600, 1090));
        PanelComponentes.setVerifyInputWhenFocusTarget(false);

        LabelTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        LabelTitulo.setText("AGREGAR ANTECEDENTES");
        LabelTitulo.setToolTipText("");

        txtCedula.setBackground(new java.awt.Color(240, 240, 240));
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lbTipoDelito.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbTipoDelito.setText("Tipo de Delito:");
        lbTipoDelito.setToolTipText("");

        txtNombreApellido.setBackground(new java.awt.Color(240, 240, 240));
        txtNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApellidoActionPerformed(evt);
            }
        });

        lbLinea.setText("___________________________________________________________________________________________________________________");
        lbLinea.setMaximumSize(new java.awt.Dimension(600, 14));
        lbLinea.setPreferredSize(new java.awt.Dimension(600, 14));

        lbNombreApellido.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNombreApellido.setText("Nombre y Apellido");
        lbNombreApellido.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");

        lbCedula.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbCedula.setText("Cédula");
        lbCedula.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");

        lbArt.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbArt.setText("Art:");
        lbArt.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");

        cbxTipoDelito.setBackground(new java.awt.Color(240, 240, 240));
        cbxTipoDelito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbDelito.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDelito.setText("Delito:");
        lbDelito.setToolTipText("");

        txArt.setText("N");
        txArt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txArt.setEnabled(false);
        txArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txArtActionPerformed(evt);
            }
        });

        cbDelito.setBackground(new java.awt.Color(240, 240, 240));
        cbDelito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        lbJuzgado.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbJuzgado.setText("Juzgado:");
        lbJuzgado.setToolTipText("");

        cbxJuzgados.setBackground(new java.awt.Color(240, 240, 240));
        cbxJuzgados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbDescripcionDelito1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDescripcionDelito1.setText("Descripción:");
        lbDescripcionDelito1.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");

        dcFechaInicioAudiencia.setDateFormatString("dd/MM/yyyy");
        dcFechaInicioAudiencia.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));

        lbFechaInicioAudiencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbFechaInicioAudiencia.setText("Fecha de Inicio de la Audiencia:");
        lbFechaInicioAudiencia.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("*");

        lbFechaInicioAudiencia1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbFechaInicioAudiencia1.setText("Fecha de Finalización de la Audiencia:");
        lbFechaInicioAudiencia1.setToolTipText("");

        dcFechaFinalizacionAudiencia.setDateFormatString("dd/MM/yyyy");
        dcFechaFinalizacionAudiencia.setIcon(new ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));

        lbDuracionAudiencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbDuracionAudiencia.setText("Duración:");
        lbDuracionAudiencia.setToolTipText("");

        txDuracionAudiencia.setText("N");
        txDuracionAudiencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txDuracionAudiencia.setEnabled(false);
        txDuracionAudiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDuracionAudienciaActionPerformed(evt);
            }
        });

        lbIntancia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbIntancia.setText("Intancia:");
        lbIntancia.setToolTipText("");

        txtIntancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntanciaActionPerformed(evt);
            }
        });

        lbNrAudiencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbNrAudiencia.setText("Nr Audiencia:");
        lbNrAudiencia.setToolTipText("");

        txtNrAudiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrAudienciaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("*");

        rbEnProceso.setBackground(new java.awt.Color(255, 255, 255));
        rbEnProceso.setSelected(true);
        rbEnProceso.setText("En Proceso");
        rbEnProceso.setFocusPainted(false);
        rbEnProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnProcesoActionPerformed(evt);
            }
        });

        rbFinalizado.setBackground(new java.awt.Color(255, 255, 255));
        rbFinalizado.setText("Finalizado");
        rbFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFinalizadoActionPerformed(evt);
            }
        });

        lbEstadoProceso.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbEstadoProceso.setText("Estado del Proceso:");
        lbEstadoProceso.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("*");

        lbTipoCondena.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbTipoCondena.setText("Tipo de Condena:");
        lbTipoCondena.setToolTipText("");

        cbxTipoCondena.setBackground(new java.awt.Color(240, 240, 240));
        cbxTipoCondena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbSentencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        lbSentencia.setText("Sentencia:");
        lbSentencia.setToolTipText("");

        txtSentencia.setColumns(20);
        txtSentencia.setRows(5);
        jScrollPane3.setViewportView(txtSentencia);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombreArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 317, 21));

        lbIconoArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/PDF file icon_page-0001.png"))); // NOI18N
        jPanel3.add(lbIconoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        IconoBorrarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCerrar.png"))); // NOI18N
        IconoBorrarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoBorrarArchivoMouseClicked(evt);
            }
        });
        jPanel3.add(IconoBorrarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, -1));

        botonSubir.setBackground(new java.awt.Color(18, 44, 82));
        botonSubir.setPreferredSize(new java.awt.Dimension(140, 46));
        botonSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSubirMouseClicked(evt);
            }
        });

        lbIconoSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoSubir.png"))); // NOI18N

        lbSubirArchivo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbSubirArchivo.setForeground(new java.awt.Color(204, 206, 223));
        lbSubirArchivo.setText("Subir Archivo");

        javax.swing.GroupLayout botonSubirLayout = new javax.swing.GroupLayout(botonSubir);
        botonSubir.setLayout(botonSubirLayout);
        botonSubirLayout.setHorizontalGroup(
            botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSubirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSubirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbIconoSubir)
                .addContainerGap())
        );
        botonSubirLayout.setVerticalGroup(
            botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonSubirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonSubirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconoSubir)
                    .addComponent(lbSubirArchivo))
                .addGap(0, 0, 0))
        );

        botonBuscar.setBackground(new java.awt.Color(18, 44, 82));
        botonBuscar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });

        IconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoBuscar1.png"))); // NOI18N

        lbBuscar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(204, 206, 223));
        lbBuscar.setText("Buscar");

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(IconoBuscar)
                .addContainerGap())
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoBuscar)
                    .addComponent(lbBuscar))
                .addGap(0, 0, 0))
        );

        botonGuardar.setBackground(new java.awt.Color(18, 44, 82));
        botonGuardar.setPreferredSize(new java.awt.Dimension(140, 46));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        lbIconoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoGuardar.png"))); // NOI18N

        lbGuardar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        lbGuardar.setForeground(new java.awt.Color(204, 206, 223));
        lbGuardar.setText("Guardar");

        javax.swing.GroupLayout botonGuardarLayout = new javax.swing.GroupLayout(botonGuardar);
        botonGuardar.setLayout(botonGuardarLayout);
        botonGuardarLayout.setHorizontalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lbIconoGuardar)
                .addContainerGap())
        );
        botonGuardarLayout.setVerticalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconoGuardar)
                    .addComponent(lbGuardar))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout PanelComponentesLayout = new javax.swing.GroupLayout(PanelComponentes);
        PanelComponentes.setLayout(PanelComponentesLayout);
        PanelComponentesLayout.setHorizontalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(LabelTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbCedula)
                        .addGap(359, 359, 359)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(lbNombreApellido))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbTipoDelito)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbDelito)
                        .addGap(61, 61, 61)
                        .addComponent(cbDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lbArt)
                        .addGap(18, 18, 18)
                        .addComponent(txArt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbDescripcionDelito1)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbFechaInicioAudiencia)
                        .addGap(56, 56, 56)
                        .addComponent(dcFechaInicioAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbTipoCondena)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoCondena, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbSentencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbEstadoProceso)
                        .addGap(18, 18, 18)
                        .addComponent(rbEnProceso)
                        .addGap(18, 18, 18)
                        .addComponent(rbFinalizado))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addComponent(lbIntancia)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIntancia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addComponent(lbNrAudiencia)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNrAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                                .addComponent(lbFechaInicioAudiencia1)
                                                .addGap(18, 18, 18)
                                                .addComponent(dcFechaFinalizacionAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(lbDuracionAudiencia)))
                                        .addGap(18, 18, 18)
                                        .addComponent(txDuracionAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lbJuzgado)
                                .addGap(46, 46, 46)
                                .addComponent(cbxJuzgados, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelComponentesLayout.setVerticalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComponentesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(LabelTitulo)
                .addGap(7, 7, 7)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbCedula)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5))
                    .addComponent(lbNombreApellido))
                .addGap(20, 20, 20)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbTipoDelito))
                    .addComponent(cbxTipoDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(cbDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txArt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDelito)
                            .addComponent(lbArt))))
                .addGap(26, 26, 26)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcionDelito1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel19))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbJuzgado))
                    .addComponent(cbxJuzgados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbFechaInicioAudiencia))
                    .addComponent(dcFechaInicioAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dcFechaFinalizacionAudiencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txDuracionAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDuracionAudiencia, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lbFechaInicioAudiencia1))
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbIntancia))
                    .addComponent(txtIntancia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbNrAudiencia))
                    .addComponent(txtNrAudiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel22))
                    .addComponent(lbEstadoProceso)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbEnProceso))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbFinalizado)))
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbTipoCondena))
                    .addComponent(cbxTipoCondena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbSentencia)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(PanelComponentes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Esconde de forma horizontal un panel
    public void esconderHorizontal(JPanel panel, boolean dashboard){
        if(dashboard == true){
            panel.setPreferredSize(new Dimension(0, panel.getHeight()));//Esconde
        }
        else{
            panel.setPreferredSize(new Dimension(213, panel.getHeight()));//Muestra
        }
        
    }
    
    //Esconde de forma vertical un panel
    public void esconderVertical(JPanel panel, boolean dashboard, JLabel boton){
        if(dashboard == true){
            panel.setPreferredSize(new Dimension(panel.getWidth(), 0));//Esconde
            cambiarImagen(boton, "/Vista/Iconos/IconoTriangulo1.png");//Cambia el icono
        }
        else{
            panel.setPreferredSize(new Dimension(panel.getWidth(), 92));//Muestra
            cambiarImagen(boton, "/Vista/Iconos/IconoTriangulo2.png");//Cambia el icono
        }
        
    }
    
    //Cambia la imagen de un icono ubicado en un JLabel
    public void cambiarImagen(JLabel button, String direccionImagen){
        ImageIcon img = new ImageIcon(getClass().getResource(direccionImagen));
        button.setIcon(img);
    }
    
    //Muestra o Esconde el menu al hacer click en el icono
    private void IconoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseClicked
        if(boolPanelMenu == true){
            esconderHorizontal(PanelMenu, boolPanelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelMenu = false;
        }
        else{
            esconderHorizontal(PanelMenu, boolPanelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelMenu = true;
        }
    }//GEN-LAST:event_IconoMenuMouseClicked

    private void IconoMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseEntered

    }//GEN-LAST:event_IconoMenuMouseEntered

    private void IconoMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseExited

    }//GEN-LAST:event_IconoMenuMouseExited

    //Muestra o Esconde los botones para gestionar los Antecedentes al hacer click
    private void IconoAntecedenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoAntecedenteMouseClicked
    if(boolPanelAntecedentes == true){
            esconderVertical(PanelAntecedentess, boolPanelAntecedentes, IconoTrianguloAntecedente);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelAntecedentes = false;
        }
        else{
            esconderVertical(PanelAntecedentess, boolPanelAntecedentes, IconoTrianguloAntecedente);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelAntecedentes = true;
        }
    }//GEN-LAST:event_IconoAntecedenteMouseClicked

    private void IconoJuzgadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoJuzgadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IconoJuzgadosMouseClicked
    
    //Muestra o Esconde los botones para gestionar la Cuenta o Cerrar Sesion al hacer click
    private void IconoSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoSettingsMouseClicked
        if(boolPanelSettings == true){
            esconderVertical(PanelSettings, boolPanelSettings, IconoTrianguloSettings);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelSettings = false;
        }
        else{
            esconderVertical(PanelSettings, boolPanelSettings, IconoTrianguloSettings);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelSettings = true;
        }
    }//GEN-LAST:event_IconoSettingsMouseClicked

    //Muestra o Esconde los botones para gestionar los datos de las Personas al hacer click
    private void IconoPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoPersonasMouseClicked
        if(boolPanelPersonas == true){
            esconderVertical(PanelPersonas, boolPanelPersonas, IconoTrianguloPersonas);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelPersonas = false;
        }
        else{
            esconderVertical(PanelPersonas, boolPanelPersonas, IconoTrianguloPersonas);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelPersonas = true;
        }
    }//GEN-LAST:event_IconoPersonasMouseClicked

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApellidoActionPerformed

    private void txArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txArtActionPerformed

    private void txDuracionAudienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDuracionAudienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDuracionAudienciaActionPerformed

    private void txtIntanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntanciaActionPerformed

    private void txtNrAudienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrAudienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrAudienciaActionPerformed

    //Al seleccionar o marcar el Radio Button (En Proceso) deshabilita este y desmarca el otro Radio Button (Finalizado)
    private void rbEnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnProcesoActionPerformed
        if (rbEnProceso.isSelected()) {
            rbEnProceso.setEnabled(false);
            rbFinalizado.setEnabled(true);
            rbFinalizado.setSelected(false);
        }
    }//GEN-LAST:event_rbEnProcesoActionPerformed

    //Al seleccionar o marcar el Radio Button (Finalizado) deshabilita este y desmarca el otro Radio Button (En Proceso)
    private void rbFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFinalizadoActionPerformed
        if (rbFinalizado.isSelected()) {
            rbFinalizado.setEnabled(false);
            rbEnProceso.setEnabled(true);
            rbEnProceso.setSelected(false);
        }
    }//GEN-LAST:event_rbFinalizadoActionPerformed

    //Da la opcion al usuario de elegir el archivo que desea subir
    private void botonSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSubirMouseClicked
        JFileChooser fc = new JFileChooser();//Creamos el objeto JFileChooser        
        int seleccion = fc.showOpenDialog(this);//Abrimos la ventana, guardamos la opcion seleccionada por el usuario        
        if (seleccion == JFileChooser.APPROVE_OPTION) { //Si el usuario selecciona aceptar
            IconoBorrarArchivo.setVisible(true);
            lbIconoArchivo.setVisible(true);            
            fichero = fc.getSelectedFile();//Seleccionamos el fichero
            lbNombreArchivo.setVisible(true);            
            lbNombreArchivo.setText(fichero.getName());//Escribimos el nombre del archivo
        }
    }//GEN-LAST:event_botonSubirMouseClicked

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
        
    }//GEN-LAST:event_botonBuscarMouseClicked

    //Ocualta los iconos del archivo, borrar archivo,donde se presenta el nombre del arhivo y vuelve al fichero nulo al borrar el archivo
    private void IconoBorrarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoBorrarArchivoMouseClicked
        IconoBorrarArchivo.setVisible(false);
        lbIconoArchivo.setVisible(false);
        lbNombreArchivo.setVisible(false);
        lbNombreArchivo.setText("");
        fichero = null;
    }//GEN-LAST:event_IconoBorrarArchivoMouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        JOptionPane.showMessageDialog(null, "Se ha guardado con éxito");
    }//GEN-LAST:event_botonGuardarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregaAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregaAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregaAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregaAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Le da un UI mejor cuando se selecciona subir archivo
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AgregaAntecedentes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(AgregaAntecedentes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(AgregaAntecedentes.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(AgregaAntecedentes.class.getName()).log(Level.SEVERE, null, ex);
                }
                new AgregaAntecedentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconoAgregarAntecedente;
    private javax.swing.JPanel IconoAntecedente;
    private javax.swing.JLabel IconoBorrarArchivo;
    private javax.swing.JLabel IconoBuscar;
    private javax.swing.JPanel IconoCerrarSesion;
    private javax.swing.JPanel IconoCuenta;
    private javax.swing.JPanel IconoEditarAntecedente;
    private javax.swing.JPanel IconoInicio;
    private javax.swing.JPanel IconoJuzgados;
    private javax.swing.JPanel IconoMenu;
    private javax.swing.JPanel IconoPersonaAgregar;
    private javax.swing.JPanel IconoPersonaEditar;
    private javax.swing.JPanel IconoPersonas;
    private javax.swing.JPanel IconoSettings;
    private javax.swing.JLabel IconoTrianguloAntecedente;
    private javax.swing.JLabel IconoTrianguloPersonas;
    private javax.swing.JLabel IconoTrianguloSettings;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelAntecedentess;
    private javax.swing.JPanel PanelComponentes;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPersonas;
    private javax.swing.JPanel PanelSettings;
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JPanel botonGuardar;
    private javax.swing.JPanel botonSubir;
    private javax.swing.JComboBox<String> cbDelito;
    private javax.swing.JComboBox<String> cbxJuzgados;
    private javax.swing.JComboBox<String> cbxTipoCondena;
    private javax.swing.JComboBox<String> cbxTipoDelito;
    private com.toedter.calendar.JDateChooser dcFechaFinalizacionAudiencia;
    private com.toedter.calendar.JDateChooser dcFechaInicioAudiencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbArt;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbDelito;
    private javax.swing.JLabel lbDescripcionDelito1;
    private javax.swing.JLabel lbDuracionAudiencia;
    private javax.swing.JLabel lbEstadoProceso;
    private javax.swing.JLabel lbFechaInicioAudiencia;
    private javax.swing.JLabel lbFechaInicioAudiencia1;
    private javax.swing.JLabel lbGuardar;
    private javax.swing.JLabel lbIconoArchivo;
    private javax.swing.JLabel lbIconoGuardar;
    private javax.swing.JLabel lbIconoSubir;
    private javax.swing.JLabel lbIntancia;
    private javax.swing.JLabel lbJuzgado;
    private javax.swing.JLabel lbLinea;
    private javax.swing.JLabel lbNombreApellido;
    private javax.swing.JLabel lbNombreArchivo;
    private javax.swing.JLabel lbNrAudiencia;
    private javax.swing.JLabel lbSentencia;
    private javax.swing.JLabel lbSubirArchivo;
    private javax.swing.JLabel lbTipoCondena;
    private javax.swing.JLabel lbTipoDelito;
    private javax.swing.JRadioButton rbEnProceso;
    private javax.swing.JRadioButton rbFinalizado;
    private javax.swing.JTextField txArt;
    private javax.swing.JTextField txDuracionAudiencia;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtIntancia;
    private javax.swing.JTextField txtNombreApellido;
    private javax.swing.JTextField txtNrAudiencia;
    private javax.swing.JTextArea txtSentencia;
    // End of variables declaration//GEN-END:variables
}
