/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class GestionarAntecedentes extends javax.swing.JFrame {

    boolean boolPanelMenu = false;
    boolean boolPanelAntecedentes = false;
    boolean boolPanelPersonas = false;
    boolean boolPanelSettings = false;
    /**
     * Creates new form VistaAntecedentes
     */
    public GestionarAntecedentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconoMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        IconoInicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IconoAntecedente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IconoTrianguloAntecedente = new javax.swing.JLabel();
        PanelAntecedentess = new javax.swing.JPanel();
        IconoAgregarAntecedente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IconoEditarAntecedente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PanelPersonas = new javax.swing.JPanel();
        IconoPersonaAgregar = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        IconoPersonaEditar = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        IconoJuzgados = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        IconoSettings = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        IconoTrianguloSettings = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IconoPersonas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IconoTrianguloPersonas = new javax.swing.JLabel();
        PanelSettings = new javax.swing.JPanel();
        IconoCuenta = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        IconoCerrarSesion = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IconoMenu.setBackground(new java.awt.Color(18, 44, 82));
        IconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconoMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconoMenuMouseExited(evt);
            }
        });
        IconoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/align-justify.png"))); // NOI18N
        IconoMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        PanelMenu.setBackground(new java.awt.Color(18, 44, 82));
        PanelMenu.setMinimumSize(new java.awt.Dimension(50, 220));
        PanelMenu.setPreferredSize(new java.awt.Dimension(0, 266));

        IconoInicio.setBackground(new java.awt.Color(18, 44, 82));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCasa1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 206, 223));
        jLabel2.setText("Inicio");

        javax.swing.GroupLayout IconoInicioLayout = new javax.swing.GroupLayout(IconoInicio);
        IconoInicio.setLayout(IconoInicioLayout);
        IconoInicioLayout.setHorizontalGroup(
            IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoInicioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoInicioLayout.setVerticalGroup(
            IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IconoAntecedente.setBackground(new java.awt.Color(18, 44, 82));
        IconoAntecedente.setPreferredSize(new java.awt.Dimension(140, 46));
        IconoAntecedente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoAntecedenteMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 206, 223));
        jLabel8.setText("Antecedentes");

        IconoTrianguloAntecedente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoAntecedenteLayout = new javax.swing.GroupLayout(IconoAntecedente);
        IconoAntecedente.setLayout(IconoAntecedenteLayout);
        IconoAntecedenteLayout.setHorizontalGroup(
            IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoTrianguloAntecedente)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoAntecedenteLayout.setVerticalGroup(
            IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAntecedenteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoTrianguloAntecedente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAntecedentess.setBackground(new java.awt.Color(18, 44, 82));
        PanelAntecedentess.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoAgregarAntecedente.setBackground(new java.awt.Color(18, 44, 82));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 206, 223));
        jLabel10.setText("Agregar");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAgregar1.png"))); // NOI18N

        javax.swing.GroupLayout IconoAgregarAntecedenteLayout = new javax.swing.GroupLayout(IconoAgregarAntecedente);
        IconoAgregarAntecedente.setLayout(IconoAgregarAntecedenteLayout);
        IconoAgregarAntecedenteLayout.setHorizontalGroup(
            IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAgregarAntecedenteLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(27, 27, 27))
        );
        IconoAgregarAntecedenteLayout.setVerticalGroup(
            IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoAgregarAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoAgregarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        IconoEditarAntecedente.setBackground(new java.awt.Color(18, 44, 82));
        IconoEditarAntecedente.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAntecedente1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 206, 223));
        jLabel14.setText("Editar");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoEditar1.png"))); // NOI18N

        javax.swing.GroupLayout IconoEditarAntecedenteLayout = new javax.swing.GroupLayout(IconoEditarAntecedente);
        IconoEditarAntecedente.setLayout(IconoEditarAntecedenteLayout);
        IconoEditarAntecedenteLayout.setHorizontalGroup(
            IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoEditarAntecedenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(44, 44, 44))
        );
        IconoEditarAntecedenteLayout.setVerticalGroup(
            IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoEditarAntecedenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoEditarAntecedenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAntecedentessLayout = new javax.swing.GroupLayout(PanelAntecedentess);
        PanelAntecedentess.setLayout(PanelAntecedentessLayout);
        PanelAntecedentessLayout.setHorizontalGroup(
            PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAntecedentessLayout.createSequentialGroup()
                .addGroup(PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IconoAgregarAntecedente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IconoEditarAntecedente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelAntecedentessLayout.setVerticalGroup(
            PanelAntecedentessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAntecedentessLayout.createSequentialGroup()
                .addComponent(IconoAgregarAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(IconoEditarAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPersonas.setBackground(new java.awt.Color(18, 44, 82));
        PanelPersonas.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoPersonaAgregar.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonaAgregar.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoAgregar1.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 206, 223));
        jLabel39.setText("Agregar");

        javax.swing.GroupLayout IconoPersonaAgregarLayout = new javax.swing.GroupLayout(IconoPersonaAgregar);
        IconoPersonaAgregar.setLayout(IconoPersonaAgregarLayout);
        IconoPersonaAgregarLayout.setHorizontalGroup(
            IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaAgregarLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(26, 26, 26))
        );
        IconoPersonaAgregarLayout.setVerticalGroup(
            IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaAgregarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoPersonaAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addContainerGap())
        );

        IconoPersonaEditar.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonaEditar.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoEditar1.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 206, 223));
        jLabel42.setText("Editar");

        javax.swing.GroupLayout IconoPersonaEditarLayout = new javax.swing.GroupLayout(IconoPersonaEditar);
        IconoPersonaEditar.setLayout(IconoPersonaEditarLayout);
        IconoPersonaEditarLayout.setHorizontalGroup(
            IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaEditarLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addGap(44, 44, 44))
        );
        IconoPersonaEditarLayout.setVerticalGroup(
            IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoPersonaEditarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoPersonaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelPersonasLayout = new javax.swing.GroupLayout(PanelPersonas);
        PanelPersonas.setLayout(PanelPersonasLayout);
        PanelPersonasLayout.setHorizontalGroup(
            PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonasLayout.createSequentialGroup()
                .addGroup(PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoPersonaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPersonasLayout.setVerticalGroup(
            PanelPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonasLayout.createSequentialGroup()
                .addComponent(IconoPersonaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconoPersonaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        IconoJuzgados.setBackground(new java.awt.Color(18, 44, 82));
        IconoJuzgados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoJuzgadosMouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoJuzgado.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 206, 223));
        jLabel24.setText("Juzgados");

        javax.swing.GroupLayout IconoJuzgadosLayout = new javax.swing.GroupLayout(IconoJuzgados);
        IconoJuzgados.setLayout(IconoJuzgadosLayout);
        IconoJuzgadosLayout.setHorizontalGroup(
            IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoJuzgadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoJuzgadosLayout.setVerticalGroup(
            IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoJuzgadosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoJuzgadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IconoSettings.setBackground(new java.awt.Color(18, 44, 82));
        IconoSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoSettingsMouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoSettings.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 206, 223));
        jLabel26.setText("Settings");

        IconoTrianguloSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoSettingsLayout = new javax.swing.GroupLayout(IconoSettings);
        IconoSettings.setLayout(IconoSettingsLayout);
        IconoSettingsLayout.setHorizontalGroup(
            IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoTrianguloSettings)
                .addGap(13, 13, 13)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IconoSettingsLayout.setVerticalGroup(
            IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoSettingsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(IconoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoTrianguloSettings, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(204, 206, 223));
        jLabel1.setText("___________________________________");

        IconoPersonas.setBackground(new java.awt.Color(18, 44, 82));
        IconoPersonas.setPreferredSize(new java.awt.Dimension(210, 46));
        IconoPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconoPersonasMouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersonas.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 206, 223));
        jLabel18.setText("Personas");

        IconoTrianguloPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoTriangulo1.png"))); // NOI18N

        javax.swing.GroupLayout IconoPersonasLayout = new javax.swing.GroupLayout(IconoPersonas);
        IconoPersonas.setLayout(IconoPersonasLayout);
        IconoPersonasLayout.setHorizontalGroup(
            IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoPersonasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(IconoTrianguloPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        IconoPersonasLayout.setVerticalGroup(
            IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconoPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconoPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(IconoTrianguloPersonas)
                    .addComponent(jLabel18))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelSettings.setBackground(new java.awt.Color(18, 44, 82));
        PanelSettings.setPreferredSize(new java.awt.Dimension(210, 0));

        IconoCuenta.setBackground(new java.awt.Color(18, 44, 82));
        IconoCuenta.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCuenta.png"))); // NOI18N

        jLabel46.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 206, 223));
        jLabel46.setText("Cuenta");

        javax.swing.GroupLayout IconoCuentaLayout = new javax.swing.GroupLayout(IconoCuenta);
        IconoCuenta.setLayout(IconoCuentaLayout);
        IconoCuentaLayout.setHorizontalGroup(
            IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCuentaLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addGap(67, 67, 67))
        );
        IconoCuentaLayout.setVerticalGroup(
            IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IconoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel44))
                .addGap(13, 13, 13))
        );

        IconoCerrarSesion.setBackground(new java.awt.Color(18, 44, 82));
        IconoCerrarSesion.setPreferredSize(new java.awt.Dimension(210, 46));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoPersona.png"))); // NOI18N

        jLabel49.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 206, 223));
        jLabel49.setText("Cerrar Sesión");

        javax.swing.GroupLayout IconoCerrarSesionLayout = new javax.swing.GroupLayout(IconoCerrarSesion);
        IconoCerrarSesion.setLayout(IconoCerrarSesionLayout);
        IconoCerrarSesionLayout.setHorizontalGroup(
            IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addGap(25, 25, 25))
        );
        IconoCerrarSesionLayout.setVerticalGroup(
            IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconoCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(IconoCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel47))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelSettingsLayout = new javax.swing.GroupLayout(PanelSettings);
        PanelSettings.setLayout(PanelSettingsLayout);
        PanelSettingsLayout.setHorizontalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addGroup(PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconoCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelSettingsLayout.setVerticalGroup(
            PanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSettingsLayout.createSequentialGroup()
                .addComponent(IconoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IconoCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconoJuzgados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PanelPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelAntecedentess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IconoSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IconoAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IconoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelSettings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(IconoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(IconoAntecedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelAntecedentess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(PanelPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IconoJuzgados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IconoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1038, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void cambiarColor(JPanel panel, Color color){
        panel.setBackground(color);
    }
    
    public void clickmenu(JPanel panel, int numberbool){
        if(numberbool == 1){
            panel.setBackground(new Color(25, 29, 74));
        }
        else{
            panel.setBackground(new Color(221,226,255));
        }
    }
    
    public void esconderHorizontal(JPanel panel, boolean dashboard){
        if(dashboard == true){
            panel.setPreferredSize(new Dimension(0, panel.getHeight()));
        }
        else{
            panel.setPreferredSize(new Dimension(213, panel.getHeight()));
        }
        
    }
    
    public void esconderVertical(JPanel panel, boolean dashboard, JLabel boton){
        if(dashboard == true){
            panel.setPreferredSize(new Dimension(panel.getWidth(), 0));
            cambiarImagen(boton, "/Vista/Iconos/IconoTriangulo1.png");
        }
        else{
            panel.setPreferredSize(new Dimension(panel.getWidth(), 92));
            cambiarImagen(boton, "/Vista/Iconos/IconoTriangulo2.png");
        }
        
    }
    
    public void cambiarImagen(JLabel button, String direccionImagen){
        ImageIcon aimg = new ImageIcon(getClass().getResource(direccionImagen));
        button.setIcon(aimg);
    }
    
    private void IconoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseClicked
        if(boolPanelMenu == true){
            esconderHorizontal(PanelMenu, boolPanelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelMenu = false;
        }
        else{
            esconderHorizontal(PanelMenu, boolPanelMenu);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelMenu = true;
        }
    }//GEN-LAST:event_IconoMenuMouseClicked

    private void IconoMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseEntered

    }//GEN-LAST:event_IconoMenuMouseEntered

    private void IconoMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMouseExited

    }//GEN-LAST:event_IconoMenuMouseExited

    private void IconoAntecedenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoAntecedenteMouseClicked
    if(boolPanelAntecedentes == true){
            esconderVertical(PanelAntecedentess, boolPanelAntecedentes, IconoTrianguloAntecedente);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelAntecedentes = false;
        }
        else{
            esconderVertical(PanelAntecedentess, boolPanelAntecedentes, IconoTrianguloAntecedente);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelAntecedentes = true;
        }
    }//GEN-LAST:event_IconoAntecedenteMouseClicked

    private void IconoJuzgadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoJuzgadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_IconoJuzgadosMouseClicked

    private void IconoSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoSettingsMouseClicked
        if(boolPanelSettings == true){
            esconderVertical(PanelSettings, boolPanelSettings, IconoTrianguloSettings);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelSettings = false;
        }
        else{
            esconderVertical(PanelSettings, boolPanelSettings, IconoTrianguloSettings);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelSettings = true;
        }
    }//GEN-LAST:event_IconoSettingsMouseClicked

    private void IconoPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoPersonasMouseClicked
        if(boolPanelPersonas == true){
            esconderVertical(PanelPersonas, boolPanelPersonas, IconoTrianguloPersonas);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelPersonas = false;
        }
        else{
            esconderVertical(PanelPersonas, boolPanelPersonas, IconoTrianguloPersonas);
            SwingUtilities.updateComponentTreeUI(this);
            boolPanelPersonas = true;
        }
    }//GEN-LAST:event_IconoPersonasMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarAntecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarAntecedentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconoAgregarAntecedente;
    private javax.swing.JPanel IconoAntecedente;
    private javax.swing.JPanel IconoCerrarSesion;
    private javax.swing.JPanel IconoCuenta;
    private javax.swing.JPanel IconoEditarAntecedente;
    private javax.swing.JPanel IconoInicio;
    private javax.swing.JPanel IconoJuzgados;
    private javax.swing.JPanel IconoMenu;
    private javax.swing.JPanel IconoPersonaAgregar;
    private javax.swing.JPanel IconoPersonaEditar;
    private javax.swing.JPanel IconoPersonas;
    private javax.swing.JPanel IconoSettings;
    private javax.swing.JLabel IconoTrianguloAntecedente;
    private javax.swing.JLabel IconoTrianguloPersonas;
    private javax.swing.JLabel IconoTrianguloSettings;
    private javax.swing.JPanel PanelAntecedentess;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPersonas;
    private javax.swing.JPanel PanelSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
