/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Acces;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Creates new form Registro
     */
    public Registro(MouseListener aL) {
        initComponents();
        CbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        btnRegresar.addMouseListener(aL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CbSexo = new javax.swing.JComboBox<>();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(610, 375));
        setPreferredSize(new java.awt.Dimension(610, 375));
        setLayout(null);

        btnRegresar.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 196, 67));
        btnRegresar.setText("<");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        add(btnRegresar);
        btnRegresar.setBounds(570, 10, 30, 30);

        jLabel3.setBackground(new java.awt.Color(51, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/juridicalogin.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setOpaque(true);
        add(jLabel3);
        jLabel3.setBounds(0, 0, 280, 380);

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Usuario");
        add(jLabel2);
        jLabel2.setBounds(300, 70, 50, 14);

        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        add(jTextField1);
        jTextField1.setBounds(300, 90, 270, 20);

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Contraseña");
        add(jLabel4);
        jLabel4.setBounds(300, 120, 80, 14);

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        add(jTextField2);
        jTextField2.setBounds(300, 140, 270, 20);

        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        add(jTextField3);
        jTextField3.setBounds(300, 190, 270, 20);

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Nombre");
        add(jLabel5);
        jLabel5.setBounds(300, 170, 80, 14);

        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        add(jTextField4);
        jTextField4.setBounds(300, 240, 270, 20);

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Fecha de nacimiento");
        add(jLabel6);
        jLabel6.setBounds(440, 270, 130, 14);

        CbSexo.setBackground(new java.awt.Color(240, 240, 240));
        CbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo" }));
        add(CbSexo);
        CbSexo.setBounds(300, 270, 110, 30);

        dcFechaNacimiento.setDateFormatString("dd/MM/yyyy");
        dcFechaNacimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/IconoCalendario2.png")));
        add(dcFechaNacimiento);
        dcFechaNacimiento.setBounds(440, 290, 130, 30);

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Apellido");
        add(jLabel7);
        jLabel7.setBounds(300, 220, 80, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Registro");
        add(jLabel8);
        jLabel8.setBounds(300, 0, 180, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setIconTextGap(-50);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        add(jLabel9);
        jLabel9.setBounds(470, 330, 103, 33);

        rSFotoCircle1.setColorBorde(new java.awt.Color(204, 204, 204));
        rSFotoCircle1.setGrosorBordePopu(1);
        add(rSFotoCircle1);
        rSFotoCircle1.setBounds(500, 30, 60, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setForeground(new Color(102,196,67));// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setForeground(new Color(102,204,102));// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseExited

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Acces/Imagenes/btn1.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbSexo;
    private javax.swing.JLabel btnRegresar;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    // End of variables declaration//GEN-END:variables
}
